esialogin/apps/about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard, name='dashboard')
]

esialogin/apps/esia/urls.py
from django.urls import path
from . import views

app_name = 'esia'
urlpatterns = [
    path('', views.index, name='index'),
    path('esia/', views.callback, name='callback')
]

esialogin/apps/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('esia/', views.esia, name='esia'),
]

esialogin/urls.py
#from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView
from about.views import dashboard

urlpatterns = [
    path('', dashboard, name = 'home'),
    path('about/', include('about.urls')),
    path('login/', include('login.urls')),
    path('esia/', include('esia.urls')),
    #path('admin/', admin.site.urls),
    url(r'^favicon\.ico$', RedirectView.as_view(url = '/static/favicon.ico')),
]

esialogin/apps/about/models.py
from django.db import models

# Create your models here.

esialogin/apps/esia/models.py
from django.db import models

# Create your models here.

esialogin/apps/login/models.py
from django.db import models

# Create your models here.

esialogin/apps/about/views.py
from django.shortcuts import render
from user.models import checkRights


@checkRights
def dashboard(request, obj_id, obj_adds):
    page_info = {
        'name': 'Главная',
        'icon': 'home',
        'br': 'Главная',
        'bp': '/about/dashboard/',
        'userinfo': obj_id
    }

    data = {
        'description': {
            'additional': 'Добро пожаловать',
            'text': 'Нет описания.',
        },
        'news': {}
    }

    return render(request, 'dashboard.html', { 'page_info': page_info, 'user_adds': obj_adds, 'data': data })

esialogin/apps/crypto/views.py
from django.shortcuts import render

# Create your views here.

esialogin/apps/esia/views.py
from django.shortcuts import render, redirect
from django.utils.http import urlencode
from django.http import HttpResponse
from crypto.models import Crypto
from base64 import b64encode, urlsafe_b64decode
from urllib import request as urllibRequest, parse as urllibParse
from esialogin.settings import SYSTEM_URL, ESIA_SCOPE, ESIA_CLIENT_ID, ESIA_TEST, SYSTEMNAME
from datetime import datetime
from pytz import timezone
import uuid
import json

import logging

log = logging.getLogger('service')
crypro = Crypto(debug = True)

if ESIA_TEST:
    authorization_base_url = 'https://esia-portal1.test.gosuslugi.ru/aas/oauth2/ac'
    token_url = 'https://esia-portal1.test.gosuslugi.ru/aas/oauth2/te'
    info_url = 'https://esia-portal1.test.gosuslugi.ru/rs/prns/'
else:
    authorization_base_url = 'https://esia.gosuslugi.ru/aas/oauth2/ac'
    token_url = 'https://esia.gosuslugi.ru/aas/oauth2/te'
    info_url = 'https://esia.gosuslugi.ru/rs/prns/'
redirect_url = '%s/%s' % (SYSTEM_URL, 'esia/esia/')



def index(request):
    removeSession(request.session)

    secret = generateSecret()
    if secret is not None:
        authorization_url = urlencode({
            'client_id': ESIA_CLIENT_ID,
            'scope': ESIA_SCOPE,
            'state': secret['state'],
            'timestamp': secret['timestamp'],
            'client_secret': secret['client_secret'],
            'response_type': 'code',
            'access_type': 'online',
            'redirect_uri': redirect_url
        })
        
        authorization_url = '%s?%s' % (authorization_base_url, authorization_url) 
        request.session['oauth_state'] = secret['state']
        
        #Редирект для авторизации пользователя в есиа и получения кода авторизации
        #Сохраняем oauth_state в сессии для проверки подлинности ответа
        return redirect(authorization_url)
    else:
        return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': 'esia error'})



def callback(request):

    if 'error' in request.GET:
        log.error('esia error: %s' % request.GET['error'])
        if 'error_description' in request.GET:
            log.error('esia error_description: %s' % request.GET['error_description'])
        return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': 'esia error'})

    if request.session.has_key('oauth_state'):
        if 'code' in request.GET and 'state' in request.GET:
            code = request.GET['code']

            #Проверяем подлинность пришедшего запроса
            if request.session['oauth_state'] == request.GET['state']:
                
                secret = generateSecret()
                if secret is not None:
                    
                    
                    
                    oauthTokenParams = {
                        'client_id': ESIA_CLIENT_ID,
                        'scope': ESIA_SCOPE,
                        'state': secret['state'],
                        'timestamp': secret['timestamp'],
                        'client_secret': secret['client_secret'],
                        'grant_type': 'authorization_code',
                        'code': code,
                        'token_type': 'Bearer',
                        'access_type': 'online',
                        'redirect_uri': redirect_url
                    }
                    
                    #По полученному коду авторизации отправляем запрос на получение токена
                    answer = getPostAnswer(url = token_url, data = oauthTokenParams, headerType = None)
                
                    if answer is None:

                        log.error('callback: token post answer is None')

                    else:

                        if 'state' in answer and 'access_token' in answer:
                            
                            #Проверяем подлинность пришедшего ответа
                            if secret['state'] == answer['state']:
                                
                                access_token = answer['access_token']
                                #Из пришедшего ответа получаем идентификатор пользователя есиа
                                oauth_sbj_id = getEsiaUserId(access_token)
                                
                                if oauth_sbj_id is not None:
                                    #log.info('callback: access_token: %s' % access_token)
                                    #log.info('callback: oauth_sbj_id: %s' % oauth_sbj_id)
                                    
                                    request.session['oauth_token'] = access_token
                                    request.session['oauth_sbj_id'] = oauth_sbj_id

                                    return redirect('login:esia')
                                        
                            else:
                                log.error('callback: esia return wrong state value')
                        else:
                            log.error('callback: state or access_token not found in answer')
                        


                else:
                    #Ошибка подписания
                    log.error('callback: sign error')

            else:
                #Созданный на первом шаге state не совпадает с пришедшим в запросе
                log.error('callback: esia return wrong state value')
        else:
            #Не корректный get запрос, возможно ктото пытается зайти на урл вручную
            log.error('callback: code or state not found in request.GET')
    else:
        #Первый шаг не пройден, возможно ктото пытается зайти на урл вручную
        log.error('callback: oauth_state not found')

    return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': 'esia error'})







def removeSession(reqSession):
    try:
        if reqSession.has_key('username') :
            del reqSession['username']
        if reqSession.has_key('sessionhash'):
            del reqSession['sessionhash']
        if reqSession.has_key('oauth_state') :
            del reqSession['oauth_state']
        if reqSession.has_key('oauth_token'):
            del reqSession['oauth_token']
        if reqSession.has_key('oauth_sbj_id'):
            del reqSession['oauth_sbj_id']
    except Exception as ex:
        log.error('removeSession Exception: {ex}'.format(ex = ex))

def generateSecret():
    state = str(uuid.uuid1())
    timestamp = datetime.now(timezone('Europe/Moscow')).strftime("%Y.%m.%d %H:%M:%S %z")
    client_secret_str = '%s%s%s%s' % (
        ESIA_SCOPE,
        timestamp,
        ESIA_CLIENT_ID,
        state
    )
    client_secret = crypro.signEsiaString(client_secret_str)
    if client_secret is not None:
        if not client_secret['error']:
            return {
                'state': state,
                'timestamp': timestamp,
                'client_secret': client_secret['signature']
            }
    return None

def getEsiaUserId(token):
    try:
        token_parts = token.split('.')
        if len(token_parts) < 3:
            return None
        #Исправляем возможный incorrect padding
        part = token_parts[1] + "==="
        partJson = urlsafe_b64decode(part.encode("utf-8")).decode("utf-8")
        partJson = json.loads(partJson)
        if 'urn:esia:sbj_id' in partJson:
            return partJson['urn:esia:sbj_id']
    except Exception as ex:
        log.error('getEsiaUserId: exception while get esiaId: %s' % ex)
    return None

def getPostAnswer(url, data, headerType = None):
    jsonResponse = None
    try:
        if headerType == 'json':
            headers = {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
            encodedData = json.dumps(data).encode('UTF-8')
        elif headerType == 'authorization':
            headers = {
                "Authorization": "Bearer %s" % data
            }
            url = '%s%s' % (info_url, url)
        else:
            headers = {}
            encodedData = urllibParse.urlencode(data).encode()

        if headerType == 'authorization':
            postRequest = urllibRequest.Request(url, headers = headers)
        else:
            postRequest = urllibRequest.Request(url, data = encodedData, headers = headers)
        
        postResponse = urllibRequest.urlopen(postRequest)
        postContent = postResponse.read().decode('UTF-8')
        jsonResponse = json.loads(postContent)
    except Exception as ex:
        log.error('getPostAnswer: post request exception: %s' % ex)
    return jsonResponse

esialogin/apps/login/views.py
from django.shortcuts import render, redirect
from user.models import UserLogin, User
from esialogin.settings import SYSTEMNAME
import logging

log = logging.getLogger('request')



def getPasswordLogin(username, password):
    loginInfo = UserLogin.objects.filter(login = username)[:1]
    loginIsCorrect = False
    sessionHash = ''
    error = ''

    if len(loginInfo) > 0:
        loginInfo = loginInfo[0]
        if not loginInfo.enabled:
            loginIsCorrect = False
            error = 'user disabled'
        else:
            loginIsCorrect = loginInfo.checkPassword(password)
            if not loginIsCorrect:
                error = 'bad user password'
    else:
        loginIsCorrect = False
        error = 'user not exist'
        
    if loginIsCorrect:
        sessionHash = loginInfo.generateRandomHash()
        loginInfo.session_hash = sessionHash
        loginInfo.save()

    return {
        'loginIsCorrect': loginIsCorrect,
        'sessionHash': sessionHash,
        'username': username,
        'error': error
    }



def index(request):
    
    if not UserLogin.isAuthCorrect(request.session)['error']:
        return redirect('about:index')
    else:
        removeSession(request.session)
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        result = getPasswordLogin(username, password)
        
        if result['loginIsCorrect']:
            request.session['username'] = result['username']
            request.session['sessionhash'] = result['sessionHash']
            return redirect('about:index')
        else:
            return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': result['error']})

    return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': ''})



def esia(request):
    userInfo = None
    
    if request.session.has_key('oauth_token') and request.session.has_key('oauth_sbj_id'):
        from esia.views import getPostAnswer
        
        oauth_token = request.session['oauth_token']
        oauth_sbj_id = request.session['oauth_sbj_id']
        
        #Отправляем запрос на получение данных из есиа: Базовые данные scope: fullname, snils
        userInfo = getPostAnswer(url = oauth_sbj_id, data = oauth_token, headerType = 'authorization')

        #Отправляем запрос на получение данных из есиа: Контакты scope: email, mobile
        #userContacts = getPostAnswer(url = '%s/ctts?embed=(elements)' % oauth_sbj_id, data = oauth_token, headerType = 'authorization')
        #log.info(userContacts)

        #Отправляем запрос на получение данных из есиа: Адрес scope: contacts
        #userAddress = getPostAnswer(url = '%s/addrs?embed=(elements)' % oauth_sbj_id, data = oauth_token, headerType = 'authorization')
        #log.info(userAddress)

    else:
        log.error('oauth_token or oauth_sbj_id not found')
        return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': 'esia error'})


    if userInfo is not None:
        if 'snils' in userInfo:
            userInfo['snils'] = userInfo['snils'].replace(' ', '').replace('-', '').strip()
        else:
            userInfo = None

    if userInfo is not None:
        result = getEsiaLogin(userInfo)
        if result['loginIsCorrect']:
            request.session['username'] = result['username']
            request.session['sessionhash'] = result['sessionHash']
            removeEsiaSession(request.session)
            return redirect('about:index')
        else:
            return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': result['error']})

    return render(request, 'login.html', {'sysname': SYSTEMNAME, 'error': ''})


def getEsiaLogin(data):
    loginIsCorrect = False
    sessionHash = ''
    error = ''

    if 'snils' in data:
        #username, password для поддержки логина по паролю
        username = data['snils']
        password = data['snils']
        
        loginIsCorrect = True
        loginInfo = UserLogin.objects.filter(snils = data['snils'])[:1]
        try:
            if len(loginInfo) > 0:
                #Если пользователь существует проверяем статус блокировки
                loginInfo = loginInfo[0]
                if not loginInfo.enabled:
                    loginIsCorrect = False
                    error = 'user disabled'

            else:
                #Если пользователя не существует создаем записи в базе
                loginInfo = UserLogin()
                loginInfo.login = username
                loginInfo.snils = data['snils']
                loginInfo.password_hash = loginInfo.getPasswordHash(password)
                loginInfo.session_hash = ''
                loginInfo.enabled = True

                userInfo = User.objects.filter(snils = data['snils'])[:1]
                if len(userInfo) > 0:
                    userInfo = userInfo[0]
                else:
                    userInfo = User()
                userInfo.fullname = ('%s %s %s' % (data['lastName'], data['firstName'], data['middleName'])).strip()
                userInfo.snils = data['snils']
                userInfo.phone = ''
                userInfo.email = ''
                userInfo.save()

                log.info('user created: login: %s, password: %s' % (loginInfo.login, password))

            sessionHash = loginInfo.generateRandomHash()
            loginInfo.session_hash = sessionHash
            loginInfo.save()
        except Exception as ex:
            loginIsCorrect = False
            error = 'runtime error'
            log.error('getEsiaLogin: %s' % ex)
    else:
        error = 'bad esia answer'
        log.error('getEsiaLogin: %s' % error)
        log.error(data)
    return {
        'loginIsCorrect': loginIsCorrect,
        'sessionHash': sessionHash,
        'username': username,
        'error': error
    }



def removeSession(reqSession):
    try:
        if reqSession.has_key('username') :
            del reqSession['username']
        if reqSession.has_key('sessionhash'):
            del reqSession['sessionhash']
    except Exception as ex:
        log.error('removeSession: %s' % ex)


def removeEsiaSession(reqSession):
    try:
        if reqSession.has_key('oauth_state'):
            del reqSession['oauth_state']
        if reqSession.has_key('oauth_token'):
            del reqSession['oauth_token']
        if reqSession.has_key('oauth_sbj_id'):
            del reqSession['oauth_sbj_id']
    except Exception as ex:
        log.error('removeEsiaSession: %s' % ex)


def logout(request):
    removeSession(request.session)
    removeEsiaSession(request.session)
    return redirect('login:index')

esialogin/apps/user/views.py
from django.shortcuts import render

# Create your views here.

esialogin/templates/ajax.html
{{page_info | safe}}

esialogin/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
    
    <div class="row">
        <div class="col-md-6">
            <div class="tile">
                <div class="tile-body">
                    
                    {% if data.description %}
                        <p><span style="font-size: 110%; font-weight: bold">{{data.description.additional}}</span></p>
                        <div>{{data.description.text | safe}}</div>
                    {% endif %}

                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="tile">
                <div class="tile-body">
                    <p><span style="font-size: 110%; font-weight: bold"><i class="fa fa-newspaper-o"></i> Новости и объявления</span></p>
                    
                    {% if data.news %}
                        {% for news in data.news %}
                            
                            <div class="card" style="margin-bottom: 25px;">
                                <div class="card-body border-primary">
                                    <p><span style="font-size: 110%; font-weight: bold">{{news.title}}</span><br><span style="font-size: 80%;">{{news.pub_date | date:'Y-m-d G-i'}}</span></p>
                                    <p>{{news.text}}</p>
                                </div>
                            </div>

                        {% endfor %}
                    {% else %}
                        <div class="card" style="margin-bottom: 25px;">
                            <div class="card-body border-primary">
                                <p><span style="font-size: 110%; font-weight: bold">Новостей не найдено.</span></p>
                            </div>
                        </div>
                    {% endif %}

                    
                </div>
            </div>
        </div>
    </div>

{% endblock %}

esialogin/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="description" content="{{user_adds.sysname}}">
        <title>{{user_adds.sysname}}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}">
    </head>

<body class="app sidebar-mini">

    
    <!-- Navbar-->
    <header class="app-header">
        <a class="app-header__logo" href="{% url 'about:index' %}">{{user_adds.shortsysname}}</a>
        <!-- Sidebar toggle button-->
        <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
        <!-- Navbar Right Menu-->
        <ul class="app-nav" style="padding-top: 5px;">
            <li><a title="Выход" class="dropdown-item" href="{% url 'login:logout' %}"><i class="fa fa-sign-out fa-lg"></i> Выход</a></li>
        </ul>
    </header>
    
    
    
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
        <div class="app-sidebar__user"><!--<img class="app-sidebar__user-avatar" src="{{user_adds.avatar}}" alt="User Image">-->
            <div>
                <p class="app-sidebar__user-name"><span style="font-size: 250%">&nbsp;<i class="fa fa-user fa-lg"></i></span> &nbsp; {{page_info.userinfo.fullname}}</p>
            </div>
        </div>
        <ul class="app-menu">
						
            <li><a class="app-menu__item" href="{% url 'about:dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a></li>

        </ul>
    </aside>
    

    
    <main class="app-content">
        <div class="app-title">
            <div style="font-size: 120%;">
                <i class="fa fa-{{page_info.icon}}"></i> &nbsp; {{page_info.name}}
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li><i class="fa fa-home"></i> / {{page_info.br}}</li>
            </ul>
        </div>
        

        {% block content %}{% endblock %}

    </main>

    <!-- Essential javascripts for application to work-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.ru.js' %}"></script>
    {% if page_info.needajax %}
        <script src="{% static 'js/ajax.js' %}"></script>
    {% endif %}
    {% block customJquery %}{% endblock %}
</body>
</html>

esialogin/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="description" content="{{sysname}}">
        <title>{{sysname}}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    </head>
<body>



    <section class="material-half-bg">
        <div class="cover"></div>
    </section>
    
    
    
    <section class="login-content">
        <div class="logo">
            <h1>{{sysname}}</h1>
        </div>
        <div class="login-box">
            <form class="login-form" method="POST" action="{% url 'login:index' %}">
                {% csrf_token %}
                <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>ВХОД</h3>
                <div class="form-group">
                    <label class="control-label">ЛОГИН</label>
					<input class="form-control" type="text" placeholder="Логин" name="username" autofocus>
                </div>
                <div class="form-group">
                    <label class="control-label">ПАРОЛЬ</label>
                    <input class="form-control" type="password" placeholder="Пароль" name="password">
                </div>
                <div class="form-group btn-container">
                    <button class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>ВОЙТИ</button>
                </div>
                <div class="form-group btn-container" style="margin-top: 15px;">
                    <a class="btn btn-primary btn-block" href="{% url 'esia:index' %}"><i class="fa fa-sign-in fa-lg fa-fw"></i>ВОЙТИ ЧЕРЕЗ ГОСУСЛУГИ</a>
                </div>
                {% ifnotequal error '' %}
                <div class="form-group btn-container">
                    <p style="text-align: center; padding-top: 3px;">{{error}}</p>
                </div>
                {% endifnotequal %}
            </form>
            
        </div>
    </section>



    <!-- Essential javascripts for application to work-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>